### Archivos PRESABER del 2014-2 al 2017-1

In [1]:
import pandas as pd
%run -i ../tools/functions.py

In [6]:
PRESABER_2014_2 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20142-RGSTRO-CLFCCN.txt", delimiter = "|", nrows=20)

In [8]:
PRESABER_2015_1 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20151-RGSTRO-CLFCCN.txt", delimiter = "|", nrows=20)

In [9]:
PRESABER_2015_2 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20152-RGSTRO-CLFCCN.txt", delimiter = "|", nrows=20)

In [10]:
PRESABER_2016_1 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20161-RGSTRO-CLFCCN.txt", delimiter = "|", nrows=20)

In [11]:
PRESABER_2016_2 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20162-RGSTRO-CLFCCN.txt", delimiter = "|", nrows=20)

EL separador usado en el archivo del 2017 es "¬", se cambiara por "|" con la herramienta <i>sed</i> de linux

In [18]:
!sed -i 's/¬/|/g' ../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20171-RGSTRO-CLFCCN_2.txt

In [19]:
PRESABER_2017_1 = pd.read_csv("../DatosFTPICFES/SABER11/SB11-PRESABER/PRESABER11-20171-RGSTRO-CLFCCN_2.txt", delimiter = "|", nrows=20)

### Se crean los Describers

In [21]:
print("File Shape", PRESABER_2014_2.shape)
print(shape_cols(PRESABER_2014_2))
PRESABER_2014_2.describe()

File Shape (20, 76)
Columns found:  32
None

,PERIODO,ESTU_EDAD,ESTU_PAIS_RESIDE,ESTU_ETNIA,ESTU_LIMITA_MOTRIZ,ESTU_LIMITA_CONDICIONESPECIAL,ESTU_LIMITA_SDOWN,ESTU_LIMITA_AUTISMO,COLE_COD_MCPIO_UBICACION,ESTU_COD_RESIDE_MCPIO,...,FAMI_EDUCA_PADRE,ESTU_OCUPACION_ACTUAL,FAMI_OCUPA_MADRE,FAMI_OCUPA_PADRE,ESTU_COD_OTRO_PAIS_PLANTEL,FAMI_PERSONAS_HOGAR,FAMI_PISOSHOGAR,FAMI_NIVEL_SISBEN,ESTU_COD_DEPTO_PRESENTACION,ESTU_COD_MCPIO_PRESENTACION
count,20.0,20.000000,20.0,4.0,0.0,0.0,0.0,0.0,9.0,20.000000,...,11.000000,11.0,11.000000,11.000000,11.0,11.000000,11.000000,11.000000,20.000000,20.000000
mean,20142.0,15.950000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,26858.500000,...,7.909091,2.0,5.000000,5.818182,1.0,4.090909,3.454545,3.818182,26.550000,26813.950000
std,0.0,1.099043,0.0,0.0,NaN,NaN,NaN,NaN,0.0,15976.243731,...,2.662876,0.0,2.408319,3.458849,0.0,1.044466,0.934199,1.662419,15.929037,16041.485003
min,20142.0,15.000000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,8001.000000,...,3.000000,2.0,2.000000,1.000000,1.0,2.000000,2.000000,1.000000,8.000000,8001.000000
25%,20142.0,15.000000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,11001.000000,...,6.500000,2.0,3.500000,3.500000,1.0,3.500000,3.000000,3.000000,11.000000,11001.000000
50%,20142.0,16.000000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,25386.000000,...,9.000000,2.0,5.000000,5.000000,1.0,4.000000,4.000000,5.000000,25.000000,25386.000000
75%,20142.0,16.000000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,29658.750000,...,9.500000,2.0,5.500000,9.000000,1.0,5.000000,4.000000,5.000000,29.000000,29388.500000
max,20142.0,19.000000,1.0,100.0,NaN,NaN,NaN,NaN,25386.0,63594.000000,...,11.000000,2.0,10.000000,12.000000,1.0,5.000000,4.000000,5.000000,63.000000,63594.000000

In [22]:
print("File Shape", PRESABER_2015_1.shape)
print(shape_cols(PRESABER_2015_1))
PRESABER_2015_1.describe()

File Shape (20, 80)
Columns found:  47
None

,PERIODO,ESTU_EDAD,ESTU_PAIS_RESIDE,ESTU_ETNIA,ESTU_LIMITA_MOTRIZ,ESTU_LIMITA_INVIDENTE,ESTU_LIMITA_CONDICIONESPECIAL,ESTU_LIMITA_SORDO,ESTU_LIMITA_SDOWN,ESTU_LIMITA_AUTISMO,...,FAMI_OCUPA_PADRE,ESTU_COD_OTRO_PAIS_PLANTEL,FAMI_PERSONAS_HOGAR,FAMI_PISOSHOGAR,ESTU_COD_PLANTEL,ESTU_RECIBE_SALARIO,FAMI_NIVEL_SISBEN,ESTU_TRABAJA,ESTU_COD_DEPTO_PRESENTACION,ESTU_COD_MCPIO_PRESENTACION
count,20.0,20.000000,20.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.00000,20.0,20.00000,20.000000,14.000000,0.0,20.000000,0.0,20.000000,20.000000
mean,20151.0,16.550000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,7.60000,1.0,4.15000,3.750000,5790.642857,NaN,4.250000,NaN,37.100000,37197.700000
std,0.0,2.038446,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.53032,0.0,1.03999,0.638666,4407.296251,NaN,1.409554,NaN,25.918699,25990.395587
min,20151.0,15.000000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.00000,1.0,2.00000,2.000000,35.000000,NaN,1.000000,NaN,11.000000,11001.000000
25%,20151.0,16.000000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,5.00000,1.0,4.00000,4.000000,2123.750000,NaN,4.500000,NaN,11.000000,11001.000000
50%,20151.0,16.000000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,8.00000,1.0,4.00000,4.000000,5240.000000,NaN,5.000000,NaN,25.000000,25290.000000
75%,20151.0,16.000000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,11.00000,1.0,5.00000,4.000000,7829.000000,NaN,5.000000,NaN,68.000000,68001.000000
max,20151.0,25.000000,1.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,...,12.00000,1.0,7.00000,4.000000,15483.000000,NaN,5.000000,NaN,76.000000,76001.000000

In [23]:
print("File Shape", PRESABER_2015_2.shape)
print(shape_cols(PRESABER_2015_2))
PRESABER_2015_2.describe()

File Shape (20, 80)
Columns found:  38
None

,PERIODO,ESTU_EDAD,ESTU_PAIS_RESIDE,ESTU_ETNIA,ESTU_LIMITA_MOTRIZ,ESTU_LIMITA_INVIDENTE,ESTU_LIMITA_CONDICIONESPECIAL,ESTU_LIMITA_SORDO,ESTU_LIMITA_SDOWN,ESTU_LIMITA_AUTISMO,...,FAMI_OCUPA_PADRE,ESTU_COD_OTRO_PAIS_PLANTEL,FAMI_PERSONAS_HOGAR,FAMI_PISOSHOGAR,ESTU_COD_PLANTEL,ESTU_RECIBE_SALARIO,FAMI_NIVEL_SISBEN,ESTU_TRABAJA,ESTU_COD_DEPTO_PRESENTACION,ESTU_COD_MCPIO_PRESENTACION
count,20.0,20.000000,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.000000,11.0,20.000000,20.000000,7.000000,0.0,20.000000,9.0,20.000000,20.000000
mean,20152.0,15.650000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.150000,1.0,3.800000,3.700000,4780.857143,NaN,4.000000,1.0,30.700000,30763.550000
std,0.0,1.182103,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.248886,0.0,0.894427,0.732695,1402.382547,NaN,1.622214,0.0,25.947518,25980.108663
min,20152.0,13.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,1.0,2.000000,2.000000,2928.000000,NaN,1.000000,1.0,8.000000,8001.000000
25%,20152.0,15.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.750000,1.0,3.000000,4.000000,3529.500000,NaN,2.750000,1.0,11.000000,11001.000000
50%,20152.0,15.500000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.000000,1.0,4.000000,4.000000,5525.000000,NaN,5.000000,1.0,20.000000,20001.000000
75%,20152.0,16.250000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.000000,1.0,4.000000,4.000000,5893.000000,NaN,5.000000,1.0,41.750000,41751.000000
max,20152.0,18.000000,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.000000,1.0,6.000000,4.000000,6168.000000,NaN,5.000000,1.0,88.000000,88001.000000

In [24]:
print("File Shape", PRESABER_2016_1.shape)
print(shape_cols(PRESABER_2016_1))
PRESABER_2016_1.describe()

File Shape (20, 83)
Columns found:  47
None

,PERIODO,ESTU_EDAD,ESTU_PAIS_RESIDE,ESTU_ETNIA,ESTU_LIMITA_MOTRIZ,ESTU_LIMITA_INVIDENTE,ESTU_LIMITA_CONDICIONESPECIAL,ESTU_LIMITA_SORDO,ESTU_LIMITA_SDOWN,ESTU_LIMITA_AUTISMO,...,PERCENTIL_LECTURA_CRITICA,DESEMP_LECTURA_CRITICA,PERCENTIL_MATEMATICAS,DESEMP_MATEMATICAS,PERCENTIL_C_NATURALES,DESEMP_C_NATURALES,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PERCENTIL_INGLES,PERCENTIL_GLOBAL
count,20.0,20.000000,20.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,20161.0,16.450000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,34.90000,2.750000,42.650000,2.700000,39.300000,2.450000,39.400000,2.300000,40.550000,38.550000
std,0.0,1.099043,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.01347,0.638666,20.045409,0.656947,19.947563,0.604805,29.101275,0.923381,25.477493,21.845089
min,20161.0,14.000000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,5.00000,2.000000,5.000000,1.000000,11.000000,2.000000,4.000000,1.000000,9.000000,7.000000
25%,20161.0,16.000000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,18.00000,2.000000,28.000000,2.000000,24.000000,2.000000,13.500000,2.000000,26.750000,19.750000
50%,20161.0,16.000000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,30.00000,3.000000,34.000000,3.000000,36.500000,2.000000,32.000000,2.000000,32.000000,37.000000
75%,20161.0,17.000000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,43.75000,3.000000,55.750000,3.000000,47.500000,3.000000,59.000000,3.000000,45.000000,49.000000
max,20161.0,18.000000,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,86.00000,4.000000,95.000000,4.000000,96.000000,4.000000,97.000000,4.000000,98.000000,97.000000

In [25]:
print("File Shape", PRESABER_2016_2.shape)
print(shape_cols(PRESABER_2016_2))
PRESABER_2016_2.describe()

File Shape (20, 76)
Columns found:  42
None

,PERIODO,ESTU_EDAD,ESTU_PAIS_RESIDE,ESTU_ETNIA,COLE_COD_MCPIO_UBICACION,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,ESTU_ZONA_RESIDE,COLE_COD_DANE_INSTITUCION,COLE_COD_ICFES,...,PERCENTIL_LECTURA_CRITICA,DESEMP_LECTURA_CRITICA,PERCENTIL_MATEMATICAS,DESEMP_MATEMATICAS,PERCENTIL_C_NATURALES,DESEMP_C_NATURALES,PERCENTIL_SOCIALES_CIUDADANAS,DESEMP_SOCIALES_CIUDADANAS,PERCENTIL_INGLES,PERCENTIL_GLOBAL
count,20.0,20.000000,20.000000,0.0,1.0,20.000000,20.000000,20.000000,1.000000e+00,1.0,...,20.000000,20.000000,20.000000,20.000000,20.000000,20.00000,20.000000,20.000000,20.000000,20.000000
mean,20162.0,19.500000,13.000000,NaN,81001.0,39.350000,39538.350000,7.750000,3.810010e+11,93161.0,...,50.300000,2.750000,45.500000,2.400000,41.950000,2.15000,47.350000,2.100000,42.850000,46.100000
std,0.0,4.861232,53.665631,NaN,NaN,30.110804,30060.805559,3.492473,NaN,NaN,...,29.863021,0.786398,28.777733,0.753937,30.880883,0.67082,28.755366,0.718185,36.266956,30.908864
min,20162.0,14.000000,1.000000,NaN,81001.0,5.000000,5266.000000,1.000000,3.810010e+11,93161.0,...,8.000000,2.000000,5.000000,1.000000,4.000000,1.00000,6.000000,1.000000,5.000000,3.000000
25%,20162.0,17.000000,1.000000,NaN,81001.0,12.500000,12683.250000,5.000000,3.810010e+11,93161.0,...,23.000000,2.000000,23.750000,2.000000,18.250000,2.00000,26.750000,2.000000,10.750000,20.250000
50%,20162.0,18.500000,1.000000,NaN,81001.0,25.000000,25252.000000,10.000000,3.810010e+11,93161.0,...,48.500000,3.000000,34.500000,2.000000,28.500000,2.00000,40.500000,2.000000,29.500000,39.500000
75%,20162.0,20.000000,1.000000,NaN,81001.0,71.500000,71501.000000,10.000000,3.810010e+11,93161.0,...,74.000000,3.000000,69.750000,3.000000,66.000000,3.00000,74.000000,3.000000,71.250000,71.000000
max,20162.0,35.000000,241.000000,NaN,81001.0,85.000000,85410.000000,10.000000,3.810010e+11,93161.0,...,98.000000,4.000000,96.000000,4.000000,91.000000,3.00000,96.000000,3.000000,99.000000,97.000000

In [26]:
print("File Shape", PRESABER_2017_1.shape)
print(shape_cols(PRESABER_2017_1))
PRESABER_2017_1.describe()

File Shape (20, 50)
Columns found:  25
None

,PERIODO,ESTU_ETNIA,ESTU_LIMITA_MOTRIZ,ESTU_LIMITA_INVIDENTE,ESTU_LIMITA_CONDICIONESPECIAL,ESTU_LIMITA_SORDO,ESTU_LIMITA_SDOWN,ESTU_LIMITA_AUTISMO,ESTU_COD_RESIDE_DEPTO,ESTU_COD_RESIDE_MCPIO,...,ESTU_COD_DEPTO_PRESENTACION,DESEMP_MATEMATICAS,PERCENTIL_MATEMATICAS,PERCENTIL_INGLES,DESEMP_C_NATURALES,PERCENTIL_C_NATURALES,DESEMP_LECTURA_CRITICA,PERCENTIL_LECTURA_CRITICA,DESEMP_SOCIALES_CIUDADANAS,PERCENTIL_SOCIALES_CIUDADANAS
count,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.000000,...,20.0,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76452.000000,...,76.0,2.250000,33.250000,40.250000,2.200000,37.550000,2.600000,34.300000,2.200000,38.800000
std,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,120.839171,...,0.0,0.638666,22.009268,14.792868,0.767772,21.490451,0.680557,24.404702,0.695852,21.799565
min,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76248.000000,...,76.0,1.000000,3.000000,22.000000,1.000000,2.000000,2.000000,3.000000,1.000000,9.000000
25%,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76452.000000,...,76.0,2.000000,12.750000,25.500000,2.000000,27.250000,2.000000,17.500000,2.000000,25.000000
50%,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76520.000000,...,76.0,2.000000,30.000000,39.000000,2.000000,36.000000,2.500000,30.000000,2.000000,38.000000
75%,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76520.000000,...,76.0,3.000000,50.250000,51.250000,3.000000,49.250000,3.000000,43.750000,2.250000,44.250000
max,20171.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.0,76520.000000,...,76.0,3.000000,78.000000,68.000000,4.000000,89.000000,4.000000,86.000000,4.000000,94.000000